### PR TITLE
Dummy-data in json file

### PR DESCRIPTION
**Pull request by croninsw**
Compiled dummy-data for each module in json file. Seems like a good start!

### CODE REVIEW

**Comment by naienko** [comment]
please add users mock data

**Review by warnercarpenter — COMMENTED** [review]
You did great

**Review by MoSilvera — APPROVED** [review]
👍

**Review by warnercarpenter — APPROVED** [review]
You did great again

**Comment by naienko** [comment]
I love I love I love your mock user

**Pull request merged**
